"""add minifigures

Revision ID: 2468f8309e0b
Revises: a8624848912a
Create Date: 2025-01-30 20:43:21.833722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2468f8309e0b'
down_revision: Union[str, None] = 'a8624848912a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legosets', sa.Column('minifigures_ids', sa.JSON(), nullable=True))
    op.add_column('legosets', sa.Column('minifigures_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legosets', 'minifigures_count')
    op.drop_column('legosets', 'minifigures_ids')
    # ### end Alembic commands ###
