"""add rating in legosets

Revision ID: 2fe37afa75b9
Revises: 2468f8309e0b
Create Date: 2025-02-10 09:53:46.985248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe37afa75b9'
down_revision: Union[str, None] = '2468f8309e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legosets', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legosets', 'rating')
    # ### end Alembic commands ###
