"""update legosets cz

Revision ID: 414ef82662c1
Revises: dc974e551db0
Create Date: 2025-01-19 15:20:45.348159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '414ef82662c1'
down_revision: Union[str, None] = 'dc974e551db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('legosets', 'ages')
    op.drop_column('legosets', 'url_name')
    op.drop_column('legosets', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legosets', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('legosets', sa.Column('url_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('legosets', sa.Column('ages', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
