"""Modificate LegoSetsOrm

Revision ID: 5394d6f5c0b5
Revises: c2ccf1216719
Create Date: 2024-12-22 14:50:16.629675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5394d6f5c0b5'
down_revision: Union[str, None] = 'c2ccf1216719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Шаг 1: Добавляем столбец как nullable (временная мера)
    op.add_column('lego_sets', sa.Column('category_name', sa.String(), nullable=True))

    # Шаг 2: Заполняем существующие строки значением по умолчанию
    op.execute("UPDATE lego_sets SET category_name = 'default_category'")  # Укажите нужное значение по умолчанию

    # Шаг 3: Делаем столбец NOT NULL
    op.alter_column('lego_sets', 'category_name', nullable=False)

    # Удаляем старый столбец
    op.drop_column('lego_sets', 'url_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lego_sets', sa.Column('url_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('lego_sets', 'category_name')
    # ### end Alembic commands ###
