"""add url_name in LegoSetsOrm

Revision ID: 630d22034d8e
Revises: 5394d6f5c0b5
Create Date: 2024-12-22 19:07:02.515560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630d22034d8e'
down_revision: Union[str, None] = '5394d6f5c0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lego_sets', sa.Column('url_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lego_sets', 'url_name')
    # ### end Alembic commands ###
