"""update pieces from str to int

Revision ID: 75ca75acb009
Revises: 414ef82662c1
Create Date: 2025-01-19 20:22:59.326657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75ca75acb009'
down_revision: Union[str, None] = '414ef82662c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legosets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('legosets', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('legosets', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column(
        "legosets",
        "pieces",
        existing_type=sa.VARCHAR(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        postgresql_using="pieces::integer"  # Явное указание преобразования
    )
    op.alter_column('legosets', 'dimensions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('legosets', 'weigh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legosets', 'weigh',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('legosets', 'dimensions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('legosets', 'pieces',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('legosets', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('legosets', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('legosets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
