"""Add Models

Revision ID: 9e672955672a
Revises: 1bb433c41414
Create Date: 2024-12-21 02:37:24.411297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e672955672a'
down_revision: Union[str, None] = '1bb433c41414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lego_sets',
    sa.Column('lego_set_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('weigh', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('ages', sa.INTEGER(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('lego_set_id')
    )
    op.create_table('lego_sets_prices',
    sa.Column('lego_set_id', sa.String(), nullable=False),
    sa.Column('prices', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('lego_set_id')
    )
    op.create_table('websites',
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('website_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websites')
    op.drop_table('lego_sets_prices')
    op.drop_table('lego_sets')
    # ### end Alembic commands ###
