"""Modificate LegoSetsOrm

Revision ID: c2ccf1216719
Revises: 9e672955672a
Create Date: 2024-12-21 02:48:51.598135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ccf1216719'
down_revision: Union[str, None] = '9e672955672a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lego_sets', sa.Column('url_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lego_sets', 'url_name')
    # ### end Alembic commands ###
