"""update website database

Revision ID: cab58ef181ea
Revises: 2e29d13c96bc
Create Date: 2025-03-14 12:59:28.641448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab58ef181ea'
down_revision: Union[str, None] = '2e29d13c96bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'link')
    # ### end Alembic commands ###
