"""update legosets

Revision ID: dc974e551db0
Revises: 52753bf0d86c
Create Date: 2025-01-19 15:03:40.844620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc974e551db0'
down_revision: Union[str, None] = '52753bf0d86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legosets', sa.Column('id', sa.String(), nullable=True))
    op.execute('UPDATE legosets SET id = lego_set_id')
    op.alter_column('legosets', 'id', nullable=False)
    op.drop_constraint('lego_sets_pkey', 'legosets', type_='primary')
    op.create_primary_key('legosets_pkey', 'legosets', ['id'])
    op.drop_column('legosets', 'lego_set_id')


    op.add_column('legosets', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('legosets', sa.Column('themeGroup', sa.String(), nullable=True))
    op.add_column('legosets', sa.Column('subtheme', sa.String(), nullable=True))
    op.add_column('legosets', sa.Column('pieces', sa.String(), nullable=True))
    op.add_column('legosets', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('legosets', sa.Column('description', sa.String(), nullable=True))
    op.add_column('legosets', sa.Column('ages_range', sa.JSON(), nullable=True))
    op.add_column('legosets', sa.Column('extendedData', sa.JSON(), nullable=True))
    op.add_column('legosets', sa.Column('launchDate', sa.DateTime(), nullable=True))
    op.add_column('legosets', sa.Column('exitDate', sa.DateTime(), nullable=True))
    op.add_column('legosets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.drop_column('legosets', 'category_name')
    # op.drop_column('legosets', 'ages')
    # op.drop_column('legosets', 'url_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legosets', sa.Column('lego_set_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('legosets', sa.Column('url_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('legosets', sa.Column('ages', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.add_column('legosets', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('legosets', 'updated_at')
    op.drop_column('legosets', 'exitDate')
    op.drop_column('legosets', 'launchDate')
    op.drop_column('legosets', 'extendedData')
    op.drop_column('legosets', 'ages_range')
    op.drop_column('legosets', 'description')
    op.drop_column('legosets', 'tags')
    op.drop_column('legosets', 'pieces')
    op.drop_column('legosets', 'subtheme')
    op.drop_column('legosets', 'themeGroup')
    op.drop_column('legosets', 'theme')
    op.drop_column('legosets', 'id')
    # ### end Alembic commands ###
