from infrastructure.interfaces_impl.website_bricklick_interface import WebsiteBricklinkInterface
from infrastructure.interfaces_impl.website_lego_interface import WebsiteLegoInterface

website_lego_interface = WebsiteLegoInterface()
website_bricklink_interface = WebsiteBricklinkInterface()
