from infrastructure.repositories_impl.lego_sets_repository_impl import LegoSetsRepositoryImpl
from infrastructure.repositories_impl.lego_sets_prices_repository_impl import LegoSetsPricesRepositoryImpl

lego_sets_repository = LegoSetsRepositoryImpl()
lego_sets_prices_repository = LegoSetsPricesRepositoryImpl()
