from infrastructure.repositories_impl.lego_sets_repository_impl import LegoSetsRepositoryImpl
from infrastructure.repositories_impl.prices_repository_impl import PriceRepositoryImpl

lego_sets_repository = LegoSetsRepositoryImpl()
prices_repository = PriceRepositoryImpl()
